<?php
/**
 * Created by PhpStorm.
 * User: Enrico
 * Date: 10/06/2015
 * Time: 11:13
 */




$url = $this->url('wator', array('action'=>'next'));
?>


<button onclick="window.location.href='<?php echo $url ?>'">NEXT</button>

<pre><?php
        foreach( $this->map as $rows ) {
            foreach( $rows as $cell ) {
                if( $cell === null ) {
                    echo ".";
                } else {
                    echo "?";
                }

            }
            echo "\n";
        }

    ?></pre>
